# Generated by Django 3.0.5 on 2020-05-08 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('emailid', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SensitiveLost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('displayflag', models.BooleanField(default=True)),
                ('postid', models.CharField(default=None, max_length=250)),
                ('cardtype', models.CharField(default='', max_length=250)),
                ('description', models.CharField(default='', max_length=250)),
                ('campuslocation', models.CharField(default='', max_length=250)),
                ('address', models.CharField(default='', max_length=250)),
                ('fourdigit', models.IntegerField(default=0)),
                ('color', models.CharField(default='', max_length=250)),
                ('timestamp', models.DateField(blank=True, default=None, null=True, verbose_name='Time Stamp')),
                ('lost_found_date', models.CharField(default='', max_length=250)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sl_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SensitiveFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('displayflag', models.BooleanField(default=True)),
                ('postid', models.CharField(default=None, max_length=250)),
                ('cardtype', models.CharField(default='', max_length=250)),
                ('description', models.CharField(default='', max_length=250)),
                ('campuslocation', models.CharField(default='', max_length=250)),
                ('address', models.CharField(default='', max_length=250)),
                ('fourdigit', models.IntegerField(default=0)),
                ('color', models.CharField(default='', max_length=250)),
                ('timestamp', models.DateField(blank=True, default=None, null=True, verbose_name='Time Stamp')),
                ('lost_found_date', models.CharField(default='', max_length=250)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sf_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralLost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('displayflag', models.BooleanField(default=True)),
                ('postid', models.CharField(default=None, max_length=250)),
                ('itemtype', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('imagelink', models.CharField(max_length=500)),
                ('campuslocation', models.CharField(max_length=250)),
                ('address', models.CharField(default='', max_length=250)),
                ('timestamp', models.DateField(blank=True, default=None, null=True, verbose_name='Time Stamp')),
                ('lost_found_date', models.CharField(default='', max_length=250)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('displayflag', models.BooleanField(default=True)),
                ('postid', models.CharField(default=None, max_length=250)),
                ('itemtype', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('imagelink', models.CharField(max_length=500)),
                ('campuslocation', models.CharField(max_length=250)),
                ('address', models.CharField(default='', max_length=250)),
                ('timestamp', models.DateField(blank=True, default=None, null=True, verbose_name='Time Stamp')),
                ('lost_found_date', models.CharField(default='', max_length=250)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gf_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
